version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 1972
      - 52795:52773
      - 53773
    volumes:
      - ./:/irisdev/app

  ftpd_server: # adapted from the post: https://blog.katastros.com/a?ID=00900-107be272-28d6-4b6a-a238-0968ad3ffb1d
    image: stilliard/pure-ftpd:hardened
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace/folder_on_disk/with the path to where you want to store the files on the host machine
      - "./data:/home/irisuser/"
      - "./passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: irisuser
      FTP_USER_PASS: sys
      FTP_USER_HOME: /home/irisuser
    restart: always